### PR TITLE
Fixes `reply.redirect()` issue and updates to HAPI 6.x

### PR DESCRIPTION
**Pull request by alexgorbatchev**
`reply.redirect()` doesn't set `response.source` it seems. This patch fixes that and updates to latest HAPI.

### CODE REVIEW

**Comment by bendrucker** [comment]
Did some general cleanup and refactoring, including fixes and coverage for everything here. Also renamed to `hapi-as-promised` in keeping with the naming convention domenic uses and I've adopted. 

Thanks for bringing this to my attention though

https://github.com/bendrucker/hapi-as-promised/compare/896896af555177fc272ec728d27cff7c03a412fe...v1.0.0

**Comment by alexgorbatchev** [comment]
The 1.0.0 might still has the redirect issue I believe.

**Comment by bendrucker** [comment]
How? Switched out the response checking which might have made sense for a super old version of Hapi (or might have just been bad code) for `response.source && typeof response.source.then === 'function'`. Pretty sure a redirect just means an empty reply body. If it's still an issue a separate PR with a failing test would be much appreciated.

**Comment by alexgorbatchev** [comment]
My bad, I wasn't paying as much attention as I should've been when I read the code. You are absolutely correct! Thanks for the great work!

**Comment by bendrucker** [comment]
No worries! This was super stale and bloated — appreciate the reminder to get it working again.

**Pull request closed without merging**
